// packages/ui/src/molecules/MoleculeTooltip/MoleculeTooltip.tsx
import { defineComponent, ref, onUnmounted, nextTick, type PropType } from 'vue'

export interface MoleculeTooltipProps {
  title?: string
  position?: 'top' | 'bottom' | 'left' | 'right'
  delay?: number
}

interface ArrowCoords {
  top: string
  left: string
  bottom: string
  right: string
  transform: string
  borders: string
  [key: string]: string
}

export const MoleculeTooltip = defineComponent({
  name: 'MoleculeTooltip',
  props: {
    title: {
      type: String as PropType<string>,
      default: '',
    },
    position: {
      type: String as PropType<'top' | 'bottom' | 'left' | 'right'>,
      default: 'top',
    },
    delay: {
      type: Number as PropType<number>,
      default: 200,
    },
  },
  setup(props, { slots }) {
    const isVisible = ref<boolean>(false)
    const isCalculating = ref<boolean>(false)
    const triggerRef = ref<HTMLElement | null>(null)
    const tooltipRef = ref<HTMLElement | null>(null)

    const coords = ref({ top: 0, left: 0 })
    const arrowCoords = ref<ArrowCoords>({
      top: '',
      left: '',
      bottom: '',
      right: '',
      transform: '',
      borders: ''
    })

    let timer: ReturnType<typeof setTimeout> | null = null
    let resizeObserver: ResizeObserver | null = null
    let rafId: number | null = null

    onUnmounted(() => {
      cleanup()
    })

    function show() {
      if (timer) clearTimeout(timer)

      isCalculating.value = true
      isVisible.value = true

      recalculatePosition()

      nextTick(() => {
        recalculatePosition()
        isCalculating.value = false
        setupListeners()
      })
    }

    function hide() {
      destroyListeners()

      if (timer) clearTimeout(timer)
      timer = setTimeout(() => {
        isVisible.value = false
      }, props.delay)
    }

    function setupListeners() {
      destroyListeners()

      if (typeof window === 'undefined') return
      window.addEventListener('resize', recalculatePosition)
      window.addEventListener('scroll', recalculatePosition, { passive: true })

      if (tooltipRef.value && typeof ResizeObserver !== 'undefined') {
        resizeObserver = new ResizeObserver(() => {
          if (rafId) cancelAnimationFrame(rafId)
          rafId = requestAnimationFrame(() => {
            recalculatePosition()
          })
        })
        resizeObserver.observe(tooltipRef.value)
      }
    }

    function destroyListeners() {
      if (typeof window !== 'undefined') {
        window.removeEventListener('resize', recalculatePosition)
        window.removeEventListener('scroll', recalculatePosition)
      }

      if (resizeObserver) {
        resizeObserver.disconnect()
        resizeObserver = null
      }
      if (rafId) {
        cancelAnimationFrame(rafId)
        rafId = null
      }
    }

    function cleanup() {
      if (timer) clearTimeout(timer)
      destroyListeners()
    }

    function recalculatePosition() {
      if (!triggerRef.value || !tooltipRef.value) return

      const trigger = triggerRef.value.getBoundingClientRect()

      const tooltipWidth = tooltipRef.value.offsetWidth || 120
      const tooltipHeight = tooltipRef.value.offsetHeight || 40

      const pad = 12
      const gap = 8
      const vw = typeof window !== 'undefined' ? window.innerWidth : 1024
      const vh = typeof window !== 'undefined' ? window.innerHeight : 768

      let actualPos: 'top' | 'bottom' | 'left' | 'right' = props.position

      if (actualPos === 'left' || actualPos === 'right') {
        const fitsLeft = trigger.left - tooltipWidth - gap >= pad
        const fitsRight = trigger.right + tooltipWidth + gap <= vw - pad

        if (actualPos === 'left' && !fitsLeft) {
          actualPos = fitsRight ? 'right' : trigger.top - tooltipHeight - gap >= pad ? 'top' : 'bottom'
        } else if (actualPos === 'right' && !fitsRight) {
          actualPos = fitsLeft ? 'left' : trigger.top - tooltipHeight - gap >= pad ? 'top' : 'bottom'
        }
      }

      if (actualPos === 'top' && trigger.top - tooltipHeight - gap < pad) {
        actualPos = 'bottom'
      } else if (actualPos === 'bottom' && trigger.bottom + tooltipHeight + gap > vh - pad) {
        actualPos = 'top'
      }

      let idealLeft = 0
      let idealTop = 0

      if (actualPos === 'top' || actualPos === 'bottom') {
        idealLeft = trigger.left + (trigger.width - tooltipWidth) / 2
        idealTop = actualPos === 'top' ? trigger.top - tooltipHeight - gap : trigger.bottom + gap
      } else {
        idealLeft = actualPos === 'left' ? trigger.left - tooltipWidth - gap : trigger.right + gap
        idealTop = trigger.top + (trigger.height - tooltipHeight) / 2
      }

      if (idealLeft < pad) idealLeft = pad
      if (idealLeft + tooltipWidth > vw - pad) idealLeft = vw - tooltipWidth - pad

      if (idealTop < pad) idealTop = pad
      if (idealTop + tooltipHeight > vh - pad) idealTop = vh - tooltipHeight - pad

      coords.value = {
        left: idealLeft - trigger.left,
        top: idealTop - trigger.top,
      }

      const triggerCenterH = trigger.left + trigger.width / 2
      const triggerCenterV = trigger.top + trigger.height / 2

      const arrow: ArrowCoords = {
        top: '',
        left: '',
        bottom: '',
        right: '',
        transform: 'rotate(45deg)',
        borders: '',
      }

      if (actualPos === 'top' || actualPos === 'bottom') {
        arrow[actualPos === 'top' ? 'bottom' : 'top'] = '-4px'
        const arrowLeft = triggerCenterH - idealLeft - 4
        arrow.left = `${Math.max(8, Math.min(tooltipWidth - 16, arrowLeft))}px`
        arrow.borders = actualPos === 'top' ? 'border-r border-b' : 'border-l border-t'
      } else {
        arrow[actualPos === 'left' ? 'right' : 'left'] = '-4px'
        const arrowTop = triggerCenterV - idealTop - 4
        arrow.top = `${Math.max(8, Math.min(tooltipHeight - 16, arrowTop))}px`
        arrow.borders = actualPos === 'left' ? 'border-r border-t' : 'border-l border-b'
      }

      arrowCoords.value = arrow
    }

    return () => (
      <div
        ref={triggerRef}
        class="molecule-tooltip relative inline-block"
        data-testid="molecule-tooltip"
        onMouseenter={show}
        onMouseleave={hide}
      >
        {slots.default ? (
          slots.default()
        ) : (
          <span class="border-foreground cursor-help border-b border-dotted">
            {props.title}
          </span>
        )}

        {isVisible.value && (
          <div
            ref={tooltipRef}
            style={
              isCalculating.value
                ? { top: '-9999px', left: '-9999px', opacity: '0' }
                : { top: `${coords.value.top}px`, left: `${coords.value.left}px` }
            }
            class="border-border bg-card text-foreground absolute z-50 w-max max-w-xs transform rounded-md border p-3 shadow-lg transition-opacity data-visible"
            onMouseenter={show}
            onMouseleave={hide}
          >
            {props.title && (
              <p class="text-muted-foreground mb-1 text-xs font-semibold tracking-wider uppercase">
                {props.title}
              </p>
            )}
            <div class="text-sm">
              {slots.content ? slots.content() : props.title}
            </div>

            {!isCalculating.value && (
              <div
                style={{
                  top: arrowCoords.value.top,
                  left: arrowCoords.value.left,
                  bottom: arrowCoords.value.bottom,
                  right: arrowCoords.value.right,
                  transform: arrowCoords.value.transform,
                }}
                class={['border-border bg-card absolute h-2 w-2', arrowCoords.value.borders]}
              />
            )}
          </div>
        )}
      </div>
    )
  },
})

export default MoleculeTooltip

// packages/ui-react/src/molecules/MoleculeTooltip/MoleculeTooltip.tsx
'use client'

import React, { useState, useRef, useEffect, useCallback, useId } from 'react'

export interface MoleculeTooltipProps {
  title?: string
  position?: 'top' | 'bottom' | 'left' | 'right'
  delay?: number
  children?: React.ReactNode
  content?: React.ReactNode
}

interface Coords {
  top: number
  left: number
}

interface ArrowCoords {
  top: string
  left: string
  bottom: string
  right: string
  transform: string
  borders: string
}

export const MoleculeTooltip = ({
  title = '',
  position = 'top',
  delay = 200,
  children,
  content,
}: MoleculeTooltipProps) => {
  const [isVisible, setIsVisible] = useState(false)
  const [isCalculating, setIsCalculating] = useState(false)

  const tooltipId = useId()

  const [coords, setCoords] = useState<Coords>({ top: 0, left: 0 })
  const [arrowCoords, setArrowCoords] = useState<ArrowCoords>({
    top: '',
    left: '',
    bottom: '',
    right: '',
    transform: '',
    borders: '',
  })

  const triggerRef = useRef<HTMLDivElement>(null)
  const tooltipRef = useRef<HTMLDivElement>(null)

  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const resizeObserverRef = useRef<ResizeObserver | null>(null)
  const rafIdRef = useRef<number | null>(null)

  const recalculatePosition = useCallback(() => {
    if (!triggerRef.current || !tooltipRef.current) return

    const trigger = triggerRef.current.getBoundingClientRect()
    const tooltipWidth = tooltipRef.current.offsetWidth
    const tooltipHeight = tooltipRef.current.offsetHeight

    const pad = 12
    const gap = 8
    const vw = window.innerWidth
    const vh = window.innerHeight

    let actualPos = position

    if (actualPos === 'left' || actualPos === 'right') {
      const fitsLeft = trigger.left - tooltipWidth - gap >= pad
      const fitsRight = trigger.right + tooltipWidth + gap <= vw - pad

      if (actualPos === 'left' && !fitsLeft) {
        actualPos = fitsRight
          ? 'right'
          : trigger.top - tooltipHeight - gap >= pad
            ? 'top'
            : 'bottom'
      } else if (actualPos === 'right' && !fitsRight) {
        actualPos = fitsLeft ? 'left' : trigger.top - tooltipHeight - gap >= pad ? 'top' : 'bottom'
      }
    }

    if (actualPos === 'top' && trigger.top - tooltipHeight - gap < pad) {
      actualPos = 'bottom'
    } else if (actualPos === 'bottom' && trigger.bottom + tooltipHeight + gap > vh - pad) {
      actualPos = 'top'
    }

    let idealLeft = 0
    let idealTop = 0

    if (actualPos === 'top' || actualPos === 'bottom') {
      idealLeft = trigger.left + (trigger.width - tooltipWidth) / 2
      idealTop = actualPos === 'top' ? trigger.top - tooltipHeight - gap : trigger.bottom + gap
    } else {
      idealLeft = actualPos === 'left' ? trigger.left - tooltipWidth - gap : trigger.right + gap
      idealTop = trigger.top + (trigger.height - tooltipHeight) / 2
    }

    if (idealLeft < pad) idealLeft = pad
    if (idealLeft + tooltipWidth > vw - pad) idealLeft = vw - tooltipWidth - pad

    if (idealTop < pad) idealTop = pad
    if (idealTop + tooltipHeight > vh - pad) idealTop = vh - tooltipHeight - pad

    setCoords({
      left: idealLeft - trigger.left,
      top: idealTop - trigger.top,
    })

    const triggerCenterH = trigger.left + trigger.width / 2
    const triggerCenterV = trigger.top + trigger.height / 2

    const arrow: ArrowCoords = {
      top: '',
      left: '',
      bottom: '',
      right: '',
      transform: 'rotate(45deg)',
      borders: '',
    }

    if (actualPos === 'top' || actualPos === 'bottom') {
      arrow[actualPos === 'top' ? 'bottom' : 'top'] = '-4px'
      const arrowLeft = triggerCenterH - idealLeft - 4
      arrow.left = `${Math.max(8, Math.min(tooltipWidth - 16, arrowLeft))}px`
      arrow.borders = actualPos === 'top' ? 'border-r border-b' : 'border-l border-t'
    } else {
      arrow[actualPos === 'left' ? 'right' : 'left'] = '-4px'
      const arrowTop = triggerCenterV - idealTop - 4
      arrow.top = `${Math.max(8, Math.min(tooltipHeight - 16, arrowTop))}px`
      arrow.borders = actualPos === 'left' ? 'border-r border-t' : 'border-l border-b'
    }

    setArrowCoords(arrow)
  }, [position])

  const destroyListeners = useCallback(() => {
    window.removeEventListener('resize', recalculatePosition)
    window.removeEventListener('scroll', recalculatePosition)

    if (resizeObserverRef.current) {
      resizeObserverRef.current.disconnect()
      resizeObserverRef.current = null
    }
    if (rafIdRef.current) {
      cancelAnimationFrame(rafIdRef.current)
      rafIdRef.current = null
    }
  }, [recalculatePosition])

  const setupListeners = useCallback(() => {
    destroyListeners()

    window.addEventListener('resize', recalculatePosition)
    window.addEventListener('scroll', recalculatePosition, { passive: true })

    if (tooltipRef.current) {
      resizeObserverRef.current = new ResizeObserver(() => {
        if (rafIdRef.current) cancelAnimationFrame(rafIdRef.current)
        rafIdRef.current = requestAnimationFrame(() => {
          recalculatePosition()
        })
      })
      resizeObserverRef.current.observe(tooltipRef.current)
    }
  }, [recalculatePosition, destroyListeners])

  const show = useCallback(() => {
    if (timerRef.current) clearTimeout(timerRef.current)

    setIsCalculating(true)
    setIsVisible(true)
  }, [])

  useEffect(() => {
    if (isVisible && isCalculating) {
      recalculatePosition()
      setIsCalculating(false)
      setupListeners()
    }
  }, [isVisible, isCalculating, recalculatePosition, setupListeners])

  const hide = useCallback(() => {
    destroyListeners()

    if (timerRef.current) clearTimeout(timerRef.current)
    timerRef.current = setTimeout(() => {
      setIsVisible(false)
    }, delay)
  }, [delay, destroyListeners])

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLDivElement>) => {
      if (e.key === 'Escape') {
        if (isVisible) {
          e.stopPropagation()
          hide()
        }
        return
      }

      if (e.key === 'Enter' || e.key === ' ') {
        const activeEl = document.activeElement
        const isInteractiveElement =
          activeEl &&
          (activeEl.tagName === 'BUTTON' ||
            activeEl.tagName === 'INPUT' ||
            activeEl.tagName === 'SELECT' ||
            activeEl.tagName === 'TEXTAREA' ||
            activeEl.getAttribute('role') === 'button')

        if (isInteractiveElement && activeEl !== triggerRef.current?.firstElementChild) {
          return
        }

        e.preventDefault()
        if (isVisible) {
          hide()
        } else {
          show()
        }
      }
    },
    [isVisible, show, hide],
  )

  useEffect(() => {
    return () => {
      if (timerRef.current) clearTimeout(timerRef.current)
      window.removeEventListener('resize', recalculatePosition)
      window.removeEventListener('scroll', recalculatePosition)
      if (resizeObserverRef.current) resizeObserverRef.current.disconnect()
      if (rafIdRef.current) cancelAnimationFrame(rafIdRef.current)
    }
  }, [recalculatePosition])

  return (
    <div
      ref={triggerRef}
      className="molecule-tooltip relative inline-block"
      data-testid="molecule-tooltip"
      onMouseEnter={show}
      onMouseLeave={hide}
      onFocus={show}
      onBlur={hide}
      onKeyDown={handleKeyDown}
    >
      {children || (
        <span
          className="border-foreground focus-visible:ring-ring cursor-help rounded border-b border-dotted px-0.5 outline-hidden transition-all focus-visible:ring-2 focus-visible:ring-offset-2"
          tabIndex={0}
          role="button"
          aria-describedby={isVisible ? tooltipId : undefined}
          onClick={() => setIsVisible((prev) => !prev)}
        >
          {title}
        </span>
      )}

      {isVisible && (
        <div
          id={tooltipId}
          ref={tooltipRef}
          role="tooltip"
          style={
            isCalculating
              ? { top: '-9999px', left: '-9999px', visibility: 'hidden' }
              : { top: `${coords.top}px`, left: `${coords.left}px` }
          }
          className={`border-border bg-card text-foreground absolute z-50 w-max max-w-xs transform rounded-md border p-3 shadow-lg transition duration-150 ${
            isCalculating ? 'scale-95 opacity-0' : 'scale-100 opacity-100 ease-out'
          }`}
          onMouseEnter={show}
          onMouseLeave={hide}
        >
          {title && (
            <p className="text-muted-foreground mb-1 text-xs font-semibold tracking-wider uppercase">
              {title}
            </p>
          )}
          <div className="text-sm">{content || title}</div>

          {!isCalculating && (
            <div
              style={{
                top: arrowCoords.top,
                left: arrowCoords.left,
                bottom: arrowCoords.bottom,
                right: arrowCoords.right,
                transform: arrowCoords.transform,
              }}
              className={`border-border bg-card absolute h-2 w-2 ${arrowCoords.borders}`}
            />
          )}
        </div>
      )}
    </div>
  )
}

export default MoleculeTooltip
