// packages/ui-react/src/atoms/AtomKeyboard/AtomKeyboard.vue
<script setup lang="ts">
interface Props {
  character: string
}

const props = withDefaults(defineProps<Props>(), {
  character: '',
})
</script>

<template>
  <kbd
    class="atom-keyboard bg-card border-border text-foreground rounded border px-1 font-mono shadow-sm"
    data-testid="atom-keyboard"
  >
    {{ character }}<span class="sr-only">atom-keyboard</span></kbd
  >
</template>

// packages/ui-react/src/atoms/AtomKeyboard/AtomKeyboard.tsx
export interface AtomKeyboardProps {
  character?: string
}

export const AtomKeyboard = ({ character = '' }: AtomKeyboardProps) => {
  return (
    <kbd
      className="atom-keyboard bg-card border-border text-foreground rounded border px-1 font-mono shadow-sm"
      data-testid="atom-keyboard"
    >
      {character}
      <span className="sr-only">atom-keyboard</span>
    </kbd>
  )
}

export default AtomKeyboard
