// packages/ui/src/molecules/MoleculeThemeToggle/MoleculeThemeToggle.vue
<script setup lang="ts">
import { ref, computed, watch, type Component } from 'vue'
import { MoleculeModal, AtomToggle, AtomSelect, AtomButton } from '../../'
import { Sun, Moon, Palette, LoaderPinwheel } from '@lucide/vue'

interface Props {
  isToggled: boolean
  currentTheme: 'light' | 'dark' | 'forest' | 'midnight' | 'ocean' | 'sunset' | 'high-contrast'
  size?: 'sm' | 'md' | 'lg'
  icon?: Component
}

const props = withDefaults(defineProps<Props>(), {
  isToggled: false,
  size: 'md',
  currentTheme: 'light',
})

const emit = defineEmits(['toggle', 'longToggle', 'setTheme'])
const showModal = ref<boolean>(false)

const optionTheme = [
  { label: 'Light', value: 'light' },
  { label: 'Dark', value: 'dark' },
  { label: 'Forest', value: 'forest' },
  { label: 'Ocean', value: 'ocean' },
  { label: 'Sunset', value: 'sunset' },
  { label: 'High Contrast', value: 'high-contrast' },
]

const selectedTheme = ref<string>(props.currentTheme)

const getIcon = computed(() =>
  showModal.value
    ? LoaderPinwheel
    : !['light', 'dark'].includes(selectedTheme.value)
      ? Palette
      : props.isToggled
        ? Moon
        : Sun,
)

function modalToggle() {
  showModal.value = true
}

function closeModal() {
  showModal.value = false
}

function handleSubmit() {
  emit('setTheme', selectedTheme.value)
  closeModal()
}

watch(
  () => props.currentTheme,
  (theme) => {
    selectedTheme.value = theme
  },
)
</script>

<template>
  <div class="theme-toggle-wrapper">
    <div class="molecule-theme-toggle" data-testid="molecule-theme-toggle">
      <AtomToggle
        :class="[{ 'animate-spin [animation-duration:2s]': showModal === true }]"
        :icon="getIcon"
        :is-toggled="isToggled"
        :size="size"
        @toggle="emit('toggle')"
        @long-toggle="modalToggle"
      />
      <span class="sr-only">molecule-theme-toggle</span>
    </div>

    <Teleport to="body">
      <div
        v-if="showModal"
        class="bg-background/50 fixed inset-0 z-50 flex items-center justify-center"
        @click="closeModal"
      >
        <div @click.stop>
          <MoleculeModal
            title="Chose more themes!"
            :show="showModal"
            hide-close
            @close="closeModal"
            class="border-border bg-card text-card-foreground relative z-50 w-full max-w-md rounded-lg border p-6 shadow-xl"
          >
            <form class="flex flex-col justify-between gap-4" @submit.prevent="handleSubmit">
              <AtomSelect v-model="selectedTheme" :options="optionTheme" class="cursor-pointer" />
              <div class="flex justify-between gap-2">
                <AtomButton size="md" variant="primary" type="submit">
                  <span>Apply</span>
                </AtomButton>
                <AtomButton size="md" variant="destructive" type="button" @click="closeModal">
                  <span>Close</span>
                </AtomButton>
              </div>
            </form>
          </MoleculeModal>
        </div>
      </div>
    </Teleport>
  </div>
</template>

// packages/ui-react/src/molecules/MoleculeThemeToggle/MoleculeThemeToggle.tsx
import { useState, useMemo, useEffect, type ElementType, type FormEvent } from 'react'
import { MoleculeModal, AtomToggle, AtomSelect, AtomButton } from '../../'
import { Sun, Moon, Palette, LoaderPinwheel } from 'lucide-react'
import { createPortal } from 'react-dom'

export type ThemeType =
  | 'light'
  | 'dark'
  | 'forest'
  | 'midnight'
  | 'ocean'
  | 'sunset'
  | 'high-contrast'

export interface MoleculeThemeToggleProps {
  isToggled?: boolean
  currentTheme?: ThemeType
  size?: 'sm' | 'md' | 'lg' | 'xl' | number
  icon?: ElementType
  onToggle?: () => void
  onLongToggle?: () => void
  onSetTheme?: (theme: string) => void
}

export const MoleculeThemeToggle = ({
  isToggled = false,
  currentTheme = 'light',
  size = 'md',
  icon,
  onToggle,
  onLongToggle,
  onSetTheme
}: MoleculeThemeToggleProps) => {
  const [showModal, setShowModal] = useState(false)
  const [selectedTheme, setSelectedTheme] = useState<string>(currentTheme)
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
  }, [])

  const optionTheme = [
    { label: 'Light', value: 'light' },
    { label: 'Dark', value: 'dark' },
    { label: 'Forest', value: 'forest' },
    { label: 'Ocean', value: 'ocean' },
    { label: 'Sunset', value: 'sunset' },
    { label: 'High Contrast', value: 'high-contrast' },
  ]

  const getIcon = useMemo(() => {
    if (showModal) return LoaderPinwheel
    if (!['light', 'dark'].includes(selectedTheme)) return Palette
    return isToggled ? Moon : Sun
  }, [showModal, selectedTheme, isToggled])

  function modalToggle() {
    setShowModal(true)
    onLongToggle?.()
  }

  function closeModal() {
    setShowModal(false)
  }

  function handleSubmit(event: FormEvent) {
    event.preventDefault()
    onSetTheme?.(selectedTheme)
    closeModal()
  }

  useEffect(() => {
    setSelectedTheme(currentTheme)
  }, [currentTheme])

  return (
    <div className="theme-toggle-wrapper font-display">
      <div className="molecule-theme-toggle" data-testid="molecule-theme-toggle">
        <AtomToggle
          icon={icon || getIcon}
          isToggled={isToggled}
          size={size}
          onToggle={() => onToggle?.()}
          onLongToggle={modalToggle}
        />
        <span className="sr-only">molecule-theme-toggle</span>
      </div>

      {mounted && createPortal(
        <MoleculeModal
          title="Choose more themes!"
          show={showModal}
          hideClose
          onClose={closeModal}
        >
          <form data-testid="theme-form" className="flex flex-col justify-between gap-4" onSubmit={handleSubmit}>
            <AtomSelect
              value={selectedTheme}
              onUpdateModelValue={(val) => setSelectedTheme(val as string)}
              options={optionTheme}
            />
            <div className="flex justify-between gap-2">
              <AtomButton size="md" variant="primary" type="submit">
                <span>Apply</span>
              </AtomButton>
              <AtomButton size="md" variant="destructive" type="button" onClick={closeModal}>
                <span>Close</span>
              </AtomButton>
            </div>
          </form>
        </MoleculeModal>,
        document.body
      )}
    </div>
  )
}

export default MoleculeThemeToggle
