// packages/ui/src/templates/TemplateDefaultPortfolio/TemplateDefaultPortfolio.vue
<script setup lang="ts"></script>

<template>
  <div
    class="template-default-portfolio flex min-h-dvh flex-col"
    data-testid="template-default-portfolio"
  >
    <slot name="header" />

    <div class="flex min-h-0 w-full flex-1 flex-col">
      <slot name="default" />
    </div>

    <slot name="footer" />
    <span class="sr-only">template-default-portfolio</span>
  </div>
</template>

// packages/ui-react/src/templates/TemplateDefaultPortfolio/TemplateDefaultPortfolio.tsx
import { type ReactNode } from 'react'

export interface TemplateDefaultPortfolioProps {
  header?: ReactNode
  footer?: ReactNode
  children?: ReactNode
}

export const TemplateDefaultPortfolio = ({
  header,
  footer,
  children
}: TemplateDefaultPortfolioProps) => {
  return (
    <div
      className="template-default-portfolio flex min-h-dvh flex-col"
      data-testid="template-default-portfolio"
    >
      {header}

      <div className="flex min-h-0 w-full flex-1 flex-col" data-testid="template-body-container">
        {children}
      </div>

      {footer}
      <span className="sr-only">template-default-portfolio</span>
    </div>
  )
}

export default TemplateDefaultPortfolio
