// packages/ui-react/src/atoms/AtomKeyboard/AtomKeyboard.tsx
export interface AtomKeyboardProps {
  character?: string
}

export const AtomKeyboard = ({ character = '' }: AtomKeyboardProps) => {
  return (
    <kbd
      className="atom-keyboard bg-card border-border text-foreground rounded border px-1 font-mono shadow-sm"
      data-testid="atom-keyboard"
    >
      {character}
      <span className="sr-only">atom-keyboard</span>
    </kbd>
  )
}

export default AtomKeyboard

// packages/ui-vue/src/atoms/AtomKeyboard/AtomKeyboard.tsx
import { defineComponent } from 'vue'

export interface AtomKeyboardProps {
  character: string
}

export default defineComponent({
  name: 'AtomKeyboard',
  props: {
    character: {
      type: String,
      default: '',
    },
  },
  setup(props) {
    return () => (
      <kbd
        class="atom-keyboard bg-card border-border text-foreground rounded border px-1 font-mono shadow-sm"
        data-testid="atom-keyboard"
      >
        {props.character}
        <span class="sr-only">atom-keyboard</span>
      </kbd>
    )
  },
})
